idf_component_register(
  SRCS
    "main.c"
    "app_runtime.c"
    "device_config.c"
    "logger.c"
    "serial_cmd.c"
    "storage.c"
    "wasm_alloc.c"
    "wifi.c"
    "bindings/bindings.c"
    "bindings/callback.c"
    "bindings/common.c"
    "bindings/env.c"
    "bindings/esp_lcd.c"
    "bindings/fs.c"
    "bindings/gfx.c"
    "bindings/gpio.c"
    "bindings/handle.c"
    "bindings/http_client.c"
    "bindings/i2c_master.c"
    "bindings/i2s_std.c"
    "bindings/output.c"
    "bindings/shared_memory.c"
    "bindings/socket.c"
    "bindings/spi_master.c"
    "bindings/storage.c"
    "bindings/task.c"
    "bindings/wasi.c"
    "bindings/websocket.c"
  INCLUDE_DIRS
    "."
)
